# Generated by Django 3.1.2 on 2020-10-31 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sender_name', models.TextField()),
                ('receiver_name', models.TextField()),
                ('total_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('paid_amount', models.FloatField()),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_app.transaction')),
            ],
        ),
    ]
