# Generated by Django 3.1.2 on 2020-10-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver_name',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sender_name',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='total_amount',
            new_name='totalAmount',
        ),
    ]
