# Generated by Django 3.1.2 on 2020-10-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0002_auto_20201031_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='paid_amount',
            new_name='paidAmount',
        ),
        migrations.RenameField(
            model_name='installment',
            old_name='transaction_id',
            new_name='parentId',
        ),
    ]
