# Generated by Django 3.1.2 on 2020-11-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_auto_20201031_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='id',
            new_name='installmentId',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='id',
            new_name='transactionId',
        ),
    ]
