# Generated by Django 3.1.2 on 2020-11-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0004_auto_20201103_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='parentId',
            new_name='parent',
        ),
    ]
