# Generated by Django 3.1.2 on 2020-11-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0005_auto_20201103_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='parent',
            new_name='parentnodes',
        ),
    ]
